### ISSUE TITLE
cell-editing not have effect  in chrome 49

### ISSUE THREAD

**Issue by huangwei16800** [mazdik/ng-mazdik#24]
cell-editing not have effect  in chrome 49, have solution ?

when parent display is flex, if not have height value, child  height:100% will not working.

**Comment by huangwei16800** [comment]
![edit](https://user-images.githubusercontent.com/28200737/58364585-ee761180-7ee0-11e9-8e20-f68d0ec69ddb.png)

**Comment by huangwei16800** [comment]
can add code for this case?  

The child element inherits the height of the parent container only if it is specified explicitly. But min-height is not an explicit specification of height, so the computed height is "auto" and not 100%.

**Comment by mazdik** [comment]
```css
.datatable-body-cell {
  height: 100%;
}
```
It works?

**Comment by huangwei16800** [comment]
had ok .
