### ISSUE TITLE
Possible to mark cell changed indicator to RowAction

### ISSUE THREAD

**Issue by hghew** [mazdik/ng-mazdik#49]
Is that a way to make the RowAction have an indicator like cell changed indicator on the top right of each cell? If there is one cell in that row have value changed, the RowAction will have an indicator as well.

That would be great for a large number of rows when scrolling through, some might miss out the cell changed indicator. Since RowAction will be the easiest way to refer if there is any row changed.

An indicator or background color highlight for RowAction would be great.

Help is much appreciated. Thanks in advance.

![Annotation 2019-08-28 104353](https://user-images.githubusercontent.com/50605037/63821812-ff6f6c80-c980-11e9-992d-aa2565671340.png)

**Comment by mazdik** [comment]
added [commit](https://github.com/mazdik/ng-crud-table/commit/43ab85779a7a78c9c57c5a2ce4e46e9078935c70)

**Comment by hghew** [comment]
thank you @mazdik
