### ISSUE TITLE
Export All

### ISSUE THREAD

**Issue by hghew** [mazdik/ng-mazdik#55]
Hi, is that a way to export all table content base on filter? (instead of the current page only)

for example, base on the filter, the total rows is 300 over total 500 rows, but pagination only shows 100 per rows, I would like to export all 300 rows.

thanks in advance.

**Comment by mazdik** [comment]
Server side (DataManager) or client side (DataTable)?
This is how it is implemented in dt-toolbar:
```ts
import { downloadCSV } from 'ng-mazdik-lib';

  downloadCsv() {
    const keys = this.table.columns.map(col => col.name);
    const titles = this.table.columns.map(col => col.title);
    downloadCSV({rows: this.table.rows, keys, titles});
  }
```
If with pagination from the server side, then you need to download all the data.
```ts
dataManager.service..getItems(requestMeta).then(data => {
    const keys = this.table.columns.map(col => col.name);
    const titles = this.table.columns.map(col => col.title);
    downloadCSV({rows: data.items, keys, titles});
});
```
[RequestMetadata](https://github.com/mazdik/ng-mazdik#custom-service)

**Comment by hghew** [comment]
hi,
i have one question, current I have select-dropdown with
[{id: '1', name: 'Something one'}, {id: '2', name: 'Something two'}]

when I export it write value 1 / 2 instead of Something one or two, can I make it write the name attribute?

**Comment by mazdik** [comment]
try
```ts
    const result = [];
    this.table.rows.forEach((x: Row) => {
      const row = x.clone();
      this.table.columns.forEach(col => {
        row[col.name] = col.getValueView(row);
      });
      result.push(row);
    });
```

**Comment by mazdik** [comment]
[update export](https://github.com/mazdik/ng-mazdik/commit/e1195e18d49f304eb70706543b5a785be1c0ef8f)

**Comment by hghew** [comment]
> [update export](https://github.com/mazdik/ng-mazdik/commit/e1195e18d49f304eb70706543b5a785be1c0ef8f)

got it for the single page export

for the customize export all, i have doubts, seems not possible to copy from PagedResult data
below is my code to export all, the data is in PagedResult

![Annotation 2019-10-29 135618](https://user-images.githubusercontent.com/50605037/67741391-eb64eb80-fa53-11e9-9b56-f4a2e58c5b10.png)

**Comment by mazdik** [comment]
```ts
  exportAllPages(): void {
    const requestMeta = {
      pageMeta: { perPage: this.dataManager.rows.length },
      filters: this.dataManager.filters,
      globalFilterValue: this.dataManager.dataFilter.globalFilterValue,
      sortMeta: this.dataManager.sorter.sortMeta
    } as RequestMetadata;

    this.dataManager.service.getItems(requestMeta).then(data => {
      const keys = this.dataManager.columns.map(col => col.name);
      const titles = this.dataManager.columns.map(col => col.title);

      const resultRows = [];
      data.items.forEach(x => {
        const row = Object.assign({}, x);
        this.dataManager.columns.forEach(col => {
          row[col.name] = col.getValueView(row);
        });
        resultRows.push(row);
      });

      downloadCSV({ rows: resultRows, keys, titles });
    });
  }
```

**Comment by hghew** [comment]
> ```ts
>   exportAllPages(): void {
>     const requestMeta = {
>       pageMeta: { perPage: this.dataManager.rows.length },
>       filters: this.dataManager.filters,
>       globalFilterValue: this.dataManager.dataFilter.globalFilterValue,
>       sortMeta: this.dataManager.sorter.sortMeta
>     } as RequestMetadata;
> 
>     this.dataManager.service.getItems(requestMeta).then(data => {
>       const keys = this.dataManager.columns.map(col => col.name);
>       const titles = this.dataManager.columns.map(col => col.title);
> 
>       const resultRows = [];
>       data.items.forEach(x => {
>         const row = Object.assign({}, x);
>         this.dataManager.columns.forEach(col => {
>           row[col.name] = col.getValueView(row);
>         });
>         resultRows.push(row);
>       });
> 
>       downloadCSV({ rows: resultRows, keys, titles });
>     });
>   }
> ```

thanks
