### ISSUE TITLE
Can i use both dtHeaderTemplate , dtRowGroupTemplate in same table.

### ISSUE THREAD

**Issue by Anzil-Aufait** [mazdik/ng-mazdik#58]
I want to use both **_dtRowGroupTemplate_** and **_dtRowGroupTemplate_** in same table. 
Is there any option to achieve this method ??

**Comment by mazdik** [comment]
Yes you can. You tried?
```ts
<app-data-table[table]="table">
  <ng-template dtHeaderTemplate></ng-template>
  <ng-template dtRowGroupTemplate let-row="row"></ng-template>
</app-data-table>
```

**Comment by Anzil-Aufait** [comment]
Yes i already tried the same and it's working fine. 

Now i want **`dtRowGroupTemplate`** for **`treeTable`**  , or 
Is there any way to create **`dtRowGroupTemplate`**  inside **`dtRowGroupTemplate`** _(as child)_ ??
