### ISSUE TITLE
Table column reorder not updating view

### ISSUE THREAD

**Issue by Anzil-Aufait** [mazdik/ng-mazdik#61]
I want to **`reorder`** table column , **when i change column order and title of column** on a button and click value changes reflect on **`table.colmn`** data , but not the view. 

`The view is not updated after the data change.`

I tried with **`ChangeDetectorRef`** , but it also updating the view.

Here is the stackblitz [**Demo**](https://stackblitz.com/edit/ng-crud-rable?embed=1&file=src/app/demo/tree-table-custom-demo.component.ts&view=preview)

**Comment by mazdik** [comment]
For example, as implemented in dt-column-toggler:
```ts
    this.table.initColumns();
    this.table.events.onRowsChanged();
    this.table.events.onResizeEnd();
```
onRowsChanged - for rows update
onResizeEnd - for columns update

**Comment by Anzil-Aufait** [comment]
@mazdik , it's working fine. 
Thank you for the update.

**Comment by Anzil-Aufait** [comment]
@mazdik , What if i want to reset **`table.columns`** after reordering the **`column`**.

I can't assign **this.table.columns** it is a read-only property.

**Comment by mazdik** [comment]
```ts
initOrders = new Map();
this.table.columns.forEach(x => this.initOrders.set(x.name, x.index));
// reset
this.table.columns.forEach(x => {x.index = this.initOrders.get(x.name); });
this.table.columns.sort((a, b) => (a.index > b.index) ? 1 : (a.index < b.index) ? -1 : 0);
```
