### ISSUE TITLE
groupRowsBy removing column from table

### ISSUE THREAD

**Issue by Anzil-Aufait** [mazdik/ng-mazdik#65]
When **`groupRowsBy`** enabled then that column is hidden from the **`dataTable column`** view. 

I also want to show **`groupRowsBy`** column , is there any option available for that ??

When i **`changecolumn.tableHidden = false;`** to **`true`** on your **`js`** file it's working file.

I also tried **`tableHidden: false`** for the **`groupRowsBy column`** but it's not working.

Adding  **`tableHidden: true`** for other **`table column`** is working.

**Comment by mazdik** [comment]
[removed](https://github.com/mazdik/ng-mazdik/commit/ec272deca9ddb7ef049132ac7f0a82fb914f75f6)

**Comment by Anzil-Aufait** [comment]
> [removed](https://github.com/mazdik/ng-mazdik/commit/ec272deca9ddb7ef049132ac7f0a82fb914f75f6)

Did you update npm package ??

**Comment by mazdik** [comment]
published version 0.0.8

**Comment by Anzil-Aufait** [comment]
@mazdik ,  Working fine.

Thank You.
