### ISSUE TITLE
column for array of objects

### ISSUE THREAD

**Issue by kush-xerovit** [mazdik/ng-mazdik#68]
is there a way to bind column value for object array like
"language": [
                    {
                        "level": "Native",
                        "language": "English"
                    },
		    {
			"level": "Native",
                        "language": "French"
		    }
                ]

**Comment by mazdik** [comment]
is array? you can try templating
cellTemplate
[demo](https://github.com/mazdik/ng-mazdik/blob/master/src/app/demo/template-demo.component.ts)

if object
column:
{title: 'Quest status', name: 'quest.status'}
rows:
[
  {
    "quest": {"quest_id": 1, "status": "COMPLETE"}
  }
]

**Comment by kush-xerovit** [comment]
Thanks,
it works
