### ISSUE TITLE
How can i get the updated column list from the datamanager after hiding the columns?

### ISSUE THREAD

**Issue by xerovit-git** [mazdik/ng-mazdik#69]
We can hide and move the positions of the column inside the action button. 
But how do we get the updated columns list? Is there any event or subscription that we can use?

**Comment by mazdik** [comment]
maybe this will help you:
```ts
  ngOnInit() {
    const subRowsChanged = this.dataManager.events.rowsChanged$.subscribe((data) => {
      console.log(this.dataManager.preparedColumns);
    });
    this.subscriptions.push(subRowsChanged);
  }
  ngOnDestroy() {
    this.subscriptions.forEach(s => s.unsubscribe());
  }
```

**Comment by mazdik** [comment]
[source](https://github.com/mazdik/ng-mazdik/blob/839489b7beb7afc667112bb41addf7d8e95d944b/projects/ng-mazdik-lib/src/lib/dt-column-toggler/dt-column-toggler.component.ts#L30)
